#!/usr/bin/env bash
# ============================================================================
# build.sh — build the scheduled-work-engine MCP server binary
# ============================================================================
# Purpose:   Produce scripts/scheduled-work-engine/bin/scheduled-work so the
#            Claude Code plugin's .mcp.json command resolves. The binary is a
#            §11.4.77 build derivative (gitignored, regenerated by this script).
# Usage:     bash plugins/scheduled-work/build.sh
# Outputs:   bin/scheduled-work; exit 0 on success.
# Dependencies: go
# Cross-references: §11.4.77 (regeneration mechanism), §11.4.164.
# Last verified: 2026-07-02
# ============================================================================
set -eu
CONST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENGINE_DIR="${CONST_DIR}/scripts/scheduled-work-engine"
if ! command -v go >/dev/null 2>&1; then
	echo "ERROR: go toolchain not found on PATH" >&2
	exit 1
fi
cd "$ENGINE_DIR"
CGO_ENABLED=0 go build -o bin/scheduled-work ./cmd/scheduled-work
echo "built: ${ENGINE_DIR}/bin/scheduled-work"
