#!/usr/bin/env bash
# scripts/generate_agent_prefix_commands.sh
#
# Generate the per-agent LAYER-2 slash-command equivalents of every registry
# action (§11.4.140). For agents that expose generated/custom commands but no
# pre-submit hook (Gemini CLI, Qwen Code, OpenAI Codex CLI), a `/background ...`
# slash command is the mechanical convenience that mirrors the free-form
# `BACKGROUND :: ...` prefix the LAYER-1 carrier block already makes work.
#
# Adding a new registry action → re-run this generator → its slash command appears
# for every supported agent. No per-action code change (registry is data).
#
# ── Purpose ──────────────────────────────────────────────────────────────────
#   Emit, for each action NAME in actions/registry.yaml:
#     actions/generated/gemini/<name>.toml   (Gemini CLI custom command)
#     actions/generated/qwen/<name>.toml     (Qwen Code custom command)
#     actions/generated/codex/<name>.md      (OpenAI Codex CLI prompts/ file)
#   Each embeds the action's expansion text and forwards the user's argument
#   (the actual task) after it.
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   bash scripts/generate_agent_prefix_commands.sh
#   HELIX_ACTION_REGISTRY=/path/to/registry.yaml \
#       bash scripts/generate_agent_prefix_commands.sh
#
# ── Inputs ───────────────────────────────────────────────────────────────────
#   $HELIX_ACTION_REGISTRY (optional) registry path; defaults via the library.
#
# ── Outputs ──────────────────────────────────────────────────────────────────
#   Generated command files under actions/generated/<agent>/ (overwritten each
#   run; deterministic; safe to re-run).
#
# ── Side-effects ─────────────────────────────────────────────────────────────
#   Creates/overwrites files under actions/generated/. No network, no state.
#
# ── Dependencies ─────────────────────────────────────────────────────────────
#   scripts/action_prefix_lib.sh.
#
# ── Cross-references ─────────────────────────────────────────────────────────
#   §11.4.140 (mandate), §11.4.28 (decoupling), §11.4.67 (parse-clean).
#
# Classification: universal (§11.4.17)

set -euo pipefail

gen_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=/dev/null
. "$gen_dir/action_prefix_lib.sh"

out_root="$gen_dir/../actions/generated"
mkdir -p "$out_root/gemini" "$out_root/qwen" "$out_root/codex"

# Lowercase a NAME for the slash-command filename / token.
apx_lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

if ! apx_validate_registry >/dev/null 2>&1; then
  echo "generate_agent_prefix_commands: registry failed validation; aborting" >&2
  exit 1
fi

# Per-agent emit helpers. Each emits ONE command file under <agent>/<basename>
# embedding the expansion + the agent's forward-arg token. `$1`=basename,
# `$2`=display-name, `$3`=expansion.
apx_emit_toml() {  # for Gemini + Qwen (identical TOML shape, {{args}} forward)
  local dir="$1" base="$2" disp="$3" exp="$4"
  {
    printf '# Generated by scripts/generate_agent_prefix_commands.sh (§11.4.140). DO NOT EDIT.\n'
    printf '# Source of truth: actions/registry.yaml action %s.\n' "$disp"
    printf 'description = "Action-prefix %s: run the task with the registered expansion applied."\n' "$disp"
    printf 'prompt = """\n'
    printf '%s\n\n' "$exp"
    printf '{{args}}\n'
    printf '"""\n'
  } > "$dir/$base.toml"
}
apx_emit_codex_md() {  # OpenAI Codex CLI prompt file ($ARGUMENTS forward)
  local dir="$1" base="$2" disp="$3" exp="$4"
  {
    printf '<!-- Generated by scripts/generate_agent_prefix_commands.sh (§11.4.140). DO NOT EDIT. -->\n'
    printf '<!-- Source of truth: actions/registry.yaml action %s. -->\n\n' "$disp"
    printf '%s\n\n' "$exp"
    printf '$ARGUMENTS\n'
  } > "$dir/$base.md"
}

count=0
while IFS= read -r name; do
  [ -n "$name" ] || continue
  expansion="$(apx_lookup_expansion "$name")" || { echo "WARN: no expansion for $name" >&2; continue; }
  lc="$(apx_lc "$name")"

  # ── Form 3 — bare slash command `/<name>` ────────────────────────────────
  #   Gemini CLI : .gemini/commands/<name>.toml
  #   Qwen Code  : .qwen/commands/<name>.toml
  #   Codex CLI  : prompts/<name>.md
  apx_emit_toml    "$out_root/gemini" "$lc" "$name" "$expansion"
  apx_emit_toml    "$out_root/qwen"   "$lc" "$name" "$expansion"
  apx_emit_codex_md "$out_root/codex"  "$lc" "$name" "$expansion"

  # ── Form 4 — namespaced slash command `/DEFAULT::<name>` ──────────────────
  # `::` is NOT a legal character in these agents' command names (the command
  # name is its filename / token), so we emit a `default-<name>` ALIAS that maps
  # to the identical expansion. Collision fallback: if `/<name>` (form 3) ever
  # collides with a host built-in command on a given agent, this alias is the
  # always-safe invocation (it mirrors the form-4 `/DEFAULT::<name>` semantics
  # the agent cannot express literally). Same expansion → equivalence preserved.
  ns_base="default-$lc"
  apx_emit_toml    "$out_root/gemini" "$ns_base" "DEFAULT::$name" "$expansion"
  apx_emit_toml    "$out_root/qwen"   "$ns_base" "DEFAULT::$name" "$expansion"
  apx_emit_codex_md "$out_root/codex"  "$ns_base" "DEFAULT::$name" "$expansion"

  count=$((count+1))
done <<APXEOF
$(apx_list_actions)
APXEOF

# A small README so the generated tree is self-explaining + the install script
# knows where to symlink/copy from.
{
  printf '# Generated action-prefix slash commands (§11.4.140)\n\n'
  printf 'Auto-generated by `scripts/generate_agent_prefix_commands.sh` from\n'
  printf '`actions/registry.yaml`. DO NOT EDIT BY HAND — re-run the generator.\n\n'
  printf 'Two slash forms per action (GRAMMAR_ADDENDUM §11.4.140):\n\n'
  printf '%s\n' '- **`<name>`** — the bare slash form 3 `/<name>`.'
  printf '%s\n' '- **`default-<name>`** — the namespaced slash form 4 `/DEFAULT::<name>`'
  printf '%s\n' '  alias (these agents disallow `::` in a command name). It maps to the'
  printf '%s\n' '  IDENTICAL expansion, so `/<name>` ≡ `/default-<name>`. **Collision'
  printf '%s\n' '  fallback:** if `/<name>` ever collides with a host built-in command on'
  printf '%s\n' '  a given agent, invoke `/default-<name>` (the always-safe form-4'
  printf '%s\n\n' '  equivalent).'
  printf 'Per-agent install targets (the install script wires these by reference):\n\n'
  printf '| Agent | Source here | Install location (consuming project) |\n'
  printf '|---|---|---|\n'
  printf '| Gemini CLI | `gemini/<name>.toml`, `gemini/default-<name>.toml` | `.gemini/commands/` |\n'
  printf '| Qwen Code  | `qwen/<name>.toml`, `qwen/default-<name>.toml`     | `.qwen/commands/` |\n'
  printf '| Codex CLI  | `codex/<name>.md`, `codex/default-<name>.md`       | `prompts/` |\n\n'
  printf 'Generated %s action(s) (each as a bare + a `default-` namespaced command).\n' "$count"
} > "$out_root/README.md"

echo "generate_agent_prefix_commands: generated $count action(s) under $out_root" >&2
