#!/usr/bin/env bash
# scripts/generate_agent_prefix_commands.sh
#
# Generate the per-agent LAYER-2 slash-command equivalents of every registry
# action (§11.4.140). For agents that expose generated/custom commands but no
# pre-submit hook (Gemini CLI, Qwen Code, OpenAI Codex CLI), a `/background ...`
# slash command is the mechanical convenience that mirrors the free-form
# `BACKGROUND :: ...` prefix the LAYER-1 carrier block already makes work.
#
# Adding a new registry action → re-run this generator → its slash command appears
# for every supported agent. No per-action code change (registry is data).
#
# ── Purpose ──────────────────────────────────────────────────────────────────
#   Emit, for each action NAME in actions/registry.yaml:
#     plugins/helix/commands/<name>.md       (Claude Code plugin slash command)
#     actions/generated/gemini/<name>.toml   (Gemini CLI custom command)
#     actions/generated/qwen/<name>.toml     (Qwen Code custom command)
#     actions/generated/codex/<name>.md      (OpenAI Codex CLI prompts/ file)
#   Each embeds the action's expansion text and forwards the user's argument
#   (the actual task) after it.
#
#   Claude Code (§11.4.140 forms 3 + 4): the plugin `helix` exposes every action
#   as BOTH a bare command `/<name>` (form 3 — honored unless a host built-in
#   collides) AND the plugin-namespaced `/helix:<name>` (form 4 — ALWAYS
#   unambiguous; Claude Code's own plugin namespacing IS the `PREFIX::ACTION`
#   escape). A `default-<name>` alias is ALSO emitted for cross-agent parity, so
#   `/default-<name>` is a collision-free invocation on EVERY agent.
#   Bare-name collisions are declared as data in the registry
#   (`slash_conflicts:`) and surfaced in each command's frontmatter/body — the
#   plugin NEVER silently shadows a host command (Claude Code resolves a
#   colliding bare name to its own built-in; the user types `/helix:<name>`).
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   bash scripts/generate_agent_prefix_commands.sh
#   HELIX_ACTION_REGISTRY=/path/to/registry.yaml \
#       bash scripts/generate_agent_prefix_commands.sh
#
# ── Inputs ───────────────────────────────────────────────────────────────────
#   $HELIX_ACTION_REGISTRY (optional) registry path; defaults via the library.
#
# ── Outputs ──────────────────────────────────────────────────────────────────
#   Generated command files under actions/generated/<agent>/ (overwritten each
#   run; deterministic; safe to re-run).
#
# ── Side-effects ─────────────────────────────────────────────────────────────
#   Creates/overwrites files under actions/generated/. No network, no state.
#
# ── Dependencies ─────────────────────────────────────────────────────────────
#   scripts/action_prefix_lib.sh.
#
# ── Cross-references ─────────────────────────────────────────────────────────
#   §11.4.140 (mandate), §11.4.28 (decoupling), §11.4.67 (parse-clean).
#
# Classification: universal (§11.4.17)

set -euo pipefail

gen_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=/dev/null
. "$gen_dir/action_prefix_lib.sh"

const_root="$(cd "$gen_dir/.." >/dev/null 2>&1 && pwd)"
# $HELIX_ACTION_OUT_ROOT redirects ALL generated output (tests / dry-runs point it
# at a sandbox). Without it, output always lands in this constitution checkout —
# so pointing $HELIX_ACTION_REGISTRY at a foreign registry would otherwise rewrite
# the REAL command tree from it. Input and output are now independently steerable.
gen_root="${HELIX_ACTION_OUT_ROOT:-$const_root}"
out_root="$gen_root/actions/generated"
# Claude Code plugin: the commands ARE the plugin's slash commands, so they are
# generated straight into the plugin tree (single source of truth — no copy).
claude_plugin_dir="$gen_root/plugins/helix"
claude_cmd_dir="$claude_plugin_dir/commands"
mkdir -p "$out_root/gemini" "$out_root/qwen" "$out_root/codex" "$claude_cmd_dir"

# PRUNE stale artefacts BEFORE regenerating. Without this, an action REMOVED from
# the registry leaves its command file behind for ever — the agent would keep
# offering a directive that no longer exists (a silent lie). Only files carrying
# our own GENERATED marker are ever deleted, so a hand-written command in the same
# directory is never touched (§9.2 — never delete what we did not write).
apx_prune() {
  local f
  for f in "$@"; do
    [ -e "$f" ] || continue
    if grep -qs 'Generated by scripts/generate_agent_prefix_commands.sh' "$f"; then
      rm -f "$f"
    fi
  done
}
apx_prune "$claude_cmd_dir"/*.md "$out_root"/gemini/*.toml "$out_root"/qwen/*.toml "$out_root"/codex/*.md

# Lowercase a NAME for the slash-command filename / token.
apx_lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# Read one scalar/list field of an action from the registry (data, not code —
# §11.4.28). Prints empty on any failure; callers fall back to a generic value.
# `slash_conflicts` is emitted space-separated.
apx_gen_field() {
  local name="$1" field="$2" reg
  reg="$(apx_registry_path)" || return 0
  python3 - "$reg" "$name" "$field" <<'PYEOF' 2>/dev/null || true
import sys
try:
    import yaml
except Exception:
    sys.exit(0)
reg, name, field = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    with open(reg) as fh:
        doc = yaml.safe_load(fh) or {}
except Exception:
    sys.exit(0)
for a in (doc.get("actions") or []):
    if a.get("name") == name:
        v = a.get(field)
        if v is None:
            break
        if isinstance(v, (list, tuple)):
            print(" ".join(str(x) for x in v))
        else:
            print(" ".join(str(v).split()))
        break
PYEOF
}

if ! apx_validate_registry >/dev/null 2>&1; then
  echo "generate_agent_prefix_commands: registry failed validation; aborting" >&2
  exit 1
fi

# Per-agent emit helpers. Each emits ONE command file under <agent>/<basename>
# embedding the expansion + the agent's forward-arg token. `$1`=basename,
# `$2`=display-name, `$3`=expansion.
apx_emit_toml() {  # for Gemini + Qwen (identical TOML shape, {{args}} forward)
  local dir="$1" base="$2" disp="$3" exp="$4"
  {
    printf '# Generated by scripts/generate_agent_prefix_commands.sh (§11.4.140). DO NOT EDIT.\n'
    printf '# Source of truth: actions/registry.yaml action %s.\n' "$disp"
    printf 'description = "Action-prefix %s: run the task with the registered expansion applied."\n' "$disp"
    printf 'prompt = """\n'
    printf '%s\n\n' "$exp"
    printf '{{args}}\n'
    printf '"""\n'
  } > "$dir/$base.toml"
}
apx_emit_codex_md() {  # OpenAI Codex CLI prompt file ($ARGUMENTS forward)
  local dir="$1" base="$2" disp="$3" exp="$4"
  {
    printf '<!-- Generated by scripts/generate_agent_prefix_commands.sh (§11.4.140). DO NOT EDIT. -->\n'
    printf '<!-- Source of truth: actions/registry.yaml action %s. -->\n\n' "$disp"
    printf '%s\n\n' "$exp"
    printf '$ARGUMENTS\n'
  } > "$dir/$base.md"
}

# Claude Code plugin slash command (YAML frontmatter + $ARGUMENTS forward).
#   $1=dir $2=basename $3=display-name $4=expansion $5=description
#   $6=space-separated colliding host command names ("" when none)
apx_emit_claude_md() {
  local dir="$1" base="$2" disp="$3" exp="$4" desc="$5" conflicts="$6"
  {
    printf -- '---\n'
    # Quote + escape the description so a `:` inside it can never break YAML.
    printf 'description: "%s"\n' "$(printf '%s' "$desc" | sed 's/\\/\\\\/g; s/"/\\"/g')"
    printf 'argument-hint: "[the task — everything after the action name]"\n'
    printf -- '---\n\n'
    printf '<!-- Generated by scripts/generate_agent_prefix_commands.sh (§11.4.140). DO NOT EDIT. -->\n'
    printf '<!-- Source of truth: actions/registry.yaml action %s. Re-run the generator to update. -->\n\n' "$disp"
    if [ -n "$conflicts" ]; then
      printf '<!-- CONFLICT (registry `slash_conflicts`): the bare form `/%s` collides with a host\n' "$base"
      printf '     built-in (%s). Claude Code resolves the bare name to its OWN built-in; invoke this\n' "$conflicts"
      printf '     action as `/helix:%s` (always unambiguous) or `/default-%s`. This plugin NEVER\n' "$base" "$base"
      printf '     silently shadows a host command. -->\n\n'
    fi
    printf '%s\n\n' "$exp"
    printf '$ARGUMENTS\n'
  } > "$dir/$base.md"
}

count=0
claude_rows=""
while IFS= read -r name; do
  [ -n "$name" ] || continue
  expansion="$(apx_lookup_expansion "$name")" || { echo "WARN: no expansion for $name" >&2; continue; }
  lc="$(apx_lc "$name")"

  # Per-action metadata (data-driven; generic fallbacks keep this non-fatal).
  summary="$(apx_gen_field "$name" summary)"
  [ -n "$summary" ] || summary="Action-prefix $name: run the task with the registered expansion applied."
  conflicts="$(apx_gen_field "$name" slash_conflicts)"

  # ── Form 3 — bare slash command `/<name>` ────────────────────────────────
  #   Claude Code: plugins/helix/commands/<name>.md  (also gives /helix:<name>)
  #   Gemini CLI : .gemini/commands/<name>.toml
  #   Qwen Code  : .qwen/commands/<name>.toml
  #   Codex CLI  : prompts/<name>.md
  apx_emit_claude_md "$claude_cmd_dir" "$lc" "$name" "$expansion" "$summary" "$conflicts"
  apx_emit_toml    "$out_root/gemini" "$lc" "$name" "$expansion"
  apx_emit_toml    "$out_root/qwen"   "$lc" "$name" "$expansion"
  apx_emit_codex_md "$out_root/codex"  "$lc" "$name" "$expansion"

  # ── Form 4 — namespaced slash command `/DEFAULT::<name>` ──────────────────
  # `::` is NOT a legal character in these agents' command names (the command
  # name is its filename / token), so we emit a `default-<name>` ALIAS that maps
  # to the identical expansion. Collision fallback: if `/<name>` (form 3) ever
  # collides with a host built-in command on a given agent, this alias is the
  # always-safe invocation (it mirrors the form-4 `/DEFAULT::<name>` semantics
  # the agent cannot express literally). Same expansion → equivalence preserved.
  ns_base="default-$lc"
  apx_emit_claude_md "$claude_cmd_dir" "$ns_base" "DEFAULT::$name" "$expansion" \
    "$summary (collision-free alias of /$lc)" ""
  apx_emit_toml    "$out_root/gemini" "$ns_base" "DEFAULT::$name" "$expansion"
  apx_emit_toml    "$out_root/qwen"   "$ns_base" "DEFAULT::$name" "$expansion"
  apx_emit_codex_md "$out_root/codex"  "$ns_base" "DEFAULT::$name" "$expansion"

  # A summary may legitimately contain `|` (e.g. "{Bug | Feature | Task}"), which
  # would break the markdown table — escape it for the cell.
  summary_cell="$(printf '%s' "$summary" | sed 's/|/\\|/g')"
  if [ -n "$conflicts" ]; then
    claude_rows="${claude_rows}| \`/helix:${lc}\` | \`/${lc}\` **COLLIDES** with host \`${conflicts}\` → use \`/helix:${lc}\` or \`/default-${lc}\` | ${summary_cell} |
"
  else
    claude_rows="${claude_rows}| \`/${lc}\` | \`/helix:${lc}\` · \`/default-${lc}\` | ${summary_cell} |
"
  fi

  count=$((count+1))
done <<APXEOF
$(apx_list_actions)
APXEOF

# Plugin README — regenerated so the command inventory can never drift from the
# registry (§11.4.12 / §11.4.60 always-in-sync).
{
  printf '# `helix` — Claude Code plugin (action directives + commands)\n\n'
  printf '**GENERATED** by `scripts/generate_agent_prefix_commands.sh` from `actions/registry.yaml`.\n'
  printf 'DO NOT EDIT BY HAND — add a registry row and re-run the generator.\n\n'
  printf 'Every registered §11.4.140 action is exposed as a Claude Code slash command.\n\n'
  printf '| Invoke | Always-unambiguous form | What it does |\n'
  printf '|---|---|---|\n'
  printf '%s\n' "$claude_rows"
  printf '## Conflict rule (§11.4.140)\n\n'
  printf 'A bare `/<name>` is honored ONLY when it does not collide with a host built-in\n'
  printf '(declared as data in the registry `slash_conflicts:` field). The plugin-namespaced\n'
  printf '`/helix:<name>` is ALWAYS unambiguous — Claude Code plugin namespacing IS the\n'
  printf '§11.4.140 form-4 `PREFIX::ACTION` escape. `/default-<name>` is a third,\n'
  printf 'collision-free form that works identically on every supported CLI agent.\n\n'
  printf 'The plugin NEVER silently shadows a host command: on a collision Claude Code\n'
  printf 'resolves the bare name to its own built-in, and the colliding command file says so.\n\n'
  printf 'Install: see `docs/actions/QUICKSTART_INSTALL.md` (one command, or fully automatic\n'
  printf 'on every constitution pull via `scripts/post_update_hook.sh` per §11.4.164).\n'
} > "$claude_plugin_dir/README.md"

# A small README so the generated tree is self-explaining + the install script
# knows where to symlink/copy from.
{
  printf '# Generated action-prefix slash commands (§11.4.140)\n\n'
  printf 'Auto-generated by `scripts/generate_agent_prefix_commands.sh` from\n'
  printf '`actions/registry.yaml`. DO NOT EDIT BY HAND — re-run the generator.\n\n'
  printf 'Two slash forms per action (GRAMMAR_ADDENDUM §11.4.140):\n\n'
  printf '%s\n' '- **`<name>`** — the bare slash form 3 `/<name>`.'
  printf '%s\n' '- **`default-<name>`** — the namespaced slash form 4 `/DEFAULT::<name>`'
  printf '%s\n' '  alias (these agents disallow `::` in a command name). It maps to the'
  printf '%s\n' '  IDENTICAL expansion, so `/<name>` ≡ `/default-<name>`. **Collision'
  printf '%s\n' '  fallback:** if `/<name>` ever collides with a host built-in command on'
  printf '%s\n' '  a given agent, invoke `/default-<name>` (the always-safe form-4'
  printf '%s\n\n' '  equivalent).'
  printf 'Per-agent install targets (the install script wires these by reference):\n\n'
  printf '| Agent | Source here | Install location (consuming project) |\n'
  printf '|---|---|---|\n'
  printf '| Gemini CLI | `gemini/<name>.toml`, `gemini/default-<name>.toml` | `.gemini/commands/` |\n'
  printf '| Qwen Code  | `qwen/<name>.toml`, `qwen/default-<name>.toml`     | `.qwen/commands/` |\n'
  printf '| Codex CLI  | `codex/<name>.md`, `codex/default-<name>.md`       | `prompts/` |\n\n'
  printf 'Generated %s action(s) (each as a bare + a `default-` namespaced command).\n' "$count"
} > "$out_root/README.md"

echo "generate_agent_prefix_commands: generated $count action(s) under $out_root" >&2
